version: '2.3'

services:
    cadvisor:
        container_name: cadvisor
        image: google/cadvisor:v0.29.0
        restart: unless-stopped
        networks:
          - service
        volumes:
          - /:/rootfs:ro
          - /sys:/sys:ro
          - /var/run:/var/run:rw
          - /var/lib/docker:/var/lib/docker:ro
        expose:
         - 8080

    influxdb:
        container_name: influxdb
        image: jsoude/influxdb-collectd
        restart: unless-stopped
        labels:
          - "traefik.frontend.rule=Host:influxdb.${MYDOMAIN}"
          - "traefik.port=8086"
        networks:
          - service
        volumes:
          - influxdb_data:/var/lib/influxdb
        expose:
          - 8086
          - 25826/udp
        ports:
          - 8086:8086
          - 25826:25826/udp

    grafana:
        container_name: grafana
        image: grafana/grafana:4.6.3
        restart: unless-stopped
        networks:
          - service
        labels:
          - "traefik.frontend.rule=Host:grafana.${MYDOMAIN}"
        #deploy:
        #  resources:
        #    limits:
        #      memory: '128M'
        #mem_limit: 256M
        expose:
          - 3000
        ports:
          - 3000:3000
        environment:
          - HTTP_USER=admin
          - HTTP_PASS=admin
          - GF_SECURITY_ADMIN_PASSWORD=PASSWORD
        volumes:
          - grafana_data:/var/lib/grafana
          - ./grafana/config:/etc/grafana
        links:
          - prometheus:prometheus
        extra_hosts:
          - "local:172.17.0.1"

    grafana5:
        container_name: grafana5
        image: grafana/grafana:5.1.3
        restart: unless-stopped
        networks:
          - service
        labels:
          - "traefik.frontend.rule=Host:grafana5.${MYDOMAIN}"
        #  - "traefik.port=300
        #deploy:
        #  resources:
        #    limits:
        #      memory: '128M'
        #mem_limit: 256M
        expose:
          - 3000
        ports:
          - 3001:3000
        environment:
          - HTTP_USER=admin
          - HTTP_PASS=admin
          - GF_SECURITY_ADMIN_PASSWORD=PASSWORD
        volumes:
          - grafana5_data:/var/lib/grafana
          - ./grafana5/config:/etc/grafana
        links:
          - prometheus:prometheus
        extra_hosts:
          - "local:172.17.0.1"


    prometheus:
        container_name: prometheus
        image: prom/prometheus:2.2.1
        restart: unless-stopped
        networks:
          - service
        labels:
          - "traefik.frontend.rule=Host:prometheus.${MYDOMAIN}"
        #deploy:
        #  resources:
        #    limits:
        #      cpus: '1.0'
        #      memory: '256M'   
        #mem_limit: 256M
        links:
          - cadvisor:cadvisor 
          - node-exporter:node-exporter
          - consul:consul
        expose:
          - 9090
        ports:
          - 9090:9090
        extra_hosts:
          - "nonso:172.17.0.1"
          - "local:172.17.0.1"
        command:
          - '--config.file=/etc/prometheus/prometheus.yml'
        volumes:
          - ./prometheus/config:/etc/prometheus
          - prometheus_data:/prometheus

    consul:
        container_name: consul
        image: consul:1.0.6
        restart: unless-stopped
        networks:
          - service
        labels:
          - "traefik.frontend.rule=Host:consul.${MYDOMAIN}"
          - "traefik.port=8500"
        links: 
          - node-exporter:node-exporter
          - cadvisor:cadvisor
        expose:
          - "8300/tcp"
          - "8301/tcp"
          - "8301/udp"
          - "8302/tcp"
          - "8302/udp"
          - "8500/tcp"
          - "8600/tcp"
          - "8600/udp"
        ports:
          - 8500:8500
          - 8600:8600
        extra_hosts:
          - "local:172.17.0.1"
          - "nonso:172.17.0.1"
          - "master:192.168.33.10"
          - "agent:192.168.33.20"
        volumes:
          - ./consul/config:/consul/config

#    registrator:
#        container_name: registrator
#        image: gliderlabs/registrator
#        networks:
#          - service
#        command: "-ip ${MYHOST} consul://${MYHOST}:8500"
#        depends_on:
#          - consul
#        labels:
#          - "traefik.frontend.rule=Host:regitrator.service.jsoude.net"
#        volumes:
#          - /var/run/docker.sock:/tmp/docker.sock       
#
        
    node-exporter:
        container_name: node-exporter
        image: prom/node-exporter
        restart: unless-stopped
        networks:
          - service
        expose:
          - 9100
        ports:
          - 9101:9100
        volumes:
          - /:/rootfs:ro
          - /sys:/host/sys:ro
          - /proc:/host/proc:ro
        
volumes:
  grafana5_data:
    driver: nfs
    driver_opts:
      share: 172.17.0.1/srv/data/volumes/grafana5_data
  grafana_data:
    driver: nfs
    driver_opts:
      share: 172.17.0.1/srv/data/volumes/grafana_data
  influxdb_data:
      driver: nfs
      driver_opts: 
        share: 172.17.0.1/srv/data/volumes/influxdb_data
  prometheus_data:
    driver: nfs
    driver_opts:
      share: 172.17.0.1/srv/data/volumes/prometheus_data

networks:
  service:
    external:
      name: service
