route:
 group_by: [cluster]
 # If an alert isn't caught by a route, send it slack.
 receiver: slack_general
 routes:
  # Send severity=slack alerts to slack.
  - receiver: slack_general
    group_by: [alertname, datacenter, app]

#  - match:
#      severity: slack
#    receiver: slack_general

receivers:
- name: slack_general
  slack_configs:
  - api_url: https://hooks.slack.com/services/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
    channel: '#code'
    text: '->alertmanager : {{ .GroupLabels.app }}/{{ .GroupLabels.alertname }}'
