global:
  scrape_interval: 2m
  scrape_timeout: 10s
  evaluation_interval: 2m
  external_labels:
    job: node
    monitor: nonso env


alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
    scheme: http
    timeout: 10s
rule_files:
- /etc/prometheus/alert.rules.yml


scrape_configs:
- job_name: service
  scrape_interval: 2m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  consul_sd_configs:
  - server: consul:8500
    tag_separator: ','
    scheme: http
    allow_stale: true
    refresh_interval: 30s
    services: []
  relabel_configs:
  - source_labels: [__meta_consul_tags]
    separator: ;
    regex: .*,monitor,.*
    replacement: $1
    action: keep
  - source_labels: [__meta_consul_service]
    separator: ;
    regex: (.*)
    target_label: service
    replacement: $1
    action: replace

- job_name: end_point_service
  params:
    module:
    - http_2xx
  scrape_interval: 2m
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  static_configs:
  - targets:
    - https://gitea.service.jsoude.net
    - http://service.jsoude.net:8080
    - https://jenkins.service.jsoude.net
    - https://grafana.service.jsoude.net
    - https://prometheus.service.jsoude.net
    - https://drone.service.jsoude.net
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    target_label: __param_target
    replacement: $1
    action: replace
  - source_labels: [__param_target]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  - separator: ;
    regex: (.*)
    target_label: __address__
    replacement: blackbox-exporter:9115
    action: replace

- job_name: jenkins
  scrape_interval: 2m
  scrape_timeout: 10s
  metrics_path: /prometheus
  scheme: https
  static_configs:
  - targets:
    - jenkins.service.jsoude.net

- job_name: traefik
  scrape_interval: 2m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  dns_sd_configs:
  - names:
    - tasks.traefik
    refresh_interval: 30s
    type: A
    port: 8080
