version: '3.2'

services:
    cadvisor:
        image: google/cadvisor:v0.30.2
        restart: unless-stopped
        deploy:
            labels:
            - "traefik.frontend.rule=Host:cadvisor.${MYDOMAIN}"
            - "traefik.port=8080"
        networks:
          - service
        volumes:
          - /:/rootfs:ro
          - /sys:/sys:ro
          - /var/run:/var/run:rw
          - /var/lib/docker:/var/lib/docker:ro
        expose:
         - 8080

    influxdb:
        image: jsoude/influxdb-collectd:1.5.3
        restart: unless-stopped
        deploy:
            labels:
            - "traefik.frontend.rule=Host:influxdb.${MYDOMAIN}"
            - "traefik.port=8086"
        networks:
          - service
        volumes:
          - influxdb_data:/var/lib/influxdb
        ports:
          - mode: host
            published: 8086
            target: 8086
          - mode: host
            published: 25826
            target: 25826
            protocol: udp

    grafana:
        image: grafana/grafana:4.6.3
        restart: unless-stopped
        networks:
          - service
        deploy:
          labels:
          - "traefik.frontend.rule=Host:grafana.${MYDOMAIN}"
          - "traefik.port=3000"
          resources:
            limits:
              memory: '256M'
        ports:
          - mode: host
            published: 3000
            target: 3000
        environment:
          - HTTP_USER=admin
          - HTTP_PASS=admin
          - GF_SECURITY_ADMIN_PASSWORD=PASSWORD
        volumes:
          - grafana_data:/var/lib/grafana
        #  - ./grafana/config:/etc/grafana
        links:
          - prometheus:prometheus
        extra_hosts:
          - "local:172.17.0.1"

    grafana5:
        container_name: grafana5
        image: grafana/grafana:5.2.1
        restart: unless-stopped
        networks:
          - service
        deploy:
            labels:
            - "traefik.frontend.rule=Host:grafana5.${MYDOMAIN}"
            - "traefik.port=3000"
            resources:
              limits:
                memory: '256M'
        environment:
          - HTTP_USER=admin
          - HTTP_PASS=admin
          - GF_SECURITY_ADMIN_PASSWORD=PASSWORD
        volumes:
          - grafana5_data:/var/lib/grafana
          - ./grafana5/config:/etc/grafana
        links:
          - prometheus:prometheus
        extra_hosts:
          - "local:172.17.0.1"


    prometheus:
        image: prom/prometheus:v2.3.2
        restart: unless-stopped
        networks:
          - service
        deploy:
          labels:
            - "traefik.frontend.rule=Host:prometheus.${MYDOMAIN}"
            - "traefik.port=9090"
          resources:
            limits:
              cpus: '1.0'
              memory: '512M'   
        links:
          - cadvisor:cadvisor 
          - node-exporter:node-exporter
          - consul:consul
          - alertmanager:alertmanager
        ports:
          - mode: host
            published: 9090
            target: 9090
        extra_hosts:
          - "nonso:172.17.0.1"
          - "local:172.17.0.1"
        command:
          - '--config.file=/etc/prometheus/prometheus.yml'
        volumes:
          - ./prometheus/config:/etc/prometheus
          - prometheus_data:/prometheus

    consul:
        image: consul:1.2.0
        restart: unless-stopped
        networks:
          - service
        deploy:
            labels:
            - "traefik.frontend.rule=Host:consul.${MYDOMAIN}"
            - "traefik.port=8500"
        links: 
          - node-exporter:node-exporter
          - cadvisor:cadvisor
        expose:
          - "8300/tcp"
          - "8301/tcp"
          - "8301/udp"
          - "8302/tcp"
          - "8302/udp"
          - "8500/tcp"
          - "8600/tcp"
          - "8600/udp"
        ports:
          - mode: host
            published: 8500
            target: 8500
          - mode: host
            published: 8600
            target: 8600
        extra_hosts:
          - "local:172.17.0.1"
          - "nonso:172.17.0.1"
          - "master:192.168.33.10"
          - "agent:192.168.33.20"
        volumes:
          - ./consul/config:/consul/config

#    registrator:
#        container_name: registrator
#        image: gliderlabs/registrator
#        networks:
#          - service
#        command: "-ip ${MYHOST} consul://${MYHOST}:8500"
#        depends_on:
#          - consul
#        labels:
#          - "traefik.frontend.rule=Host:regitrator.service.jsoude.net"
#        volumes:
#          - /var/run/docker.sock:/tmp/docker.sock       
#
        
    node-exporter:
        image: prom/node-exporter:v0.16.0
        restart: unless-stopped
        networks:
          - service
        expose:
          - 9100
        volumes:
          - /:/rootfs:ro
          - /sys:/host/sys:ro
          - /proc:/host/proc:ro

    blackbox-exporter:
        image: prom/blackbox-exporter:v0.12.0
        restart: unless-stopped
        deploy: 
            labels:
            - "traefik.frontend.rule=Host:blackbox.${MYDOMAIN}"
            - "traefik.port=9115"
        networks:
          - service
        expose:
          - 9115
        links:
          - cadvisor:cadvisor 
          - node-exporter:node-exporter
          - consul:consul
          - blackbox-exporter:blackbox-exporter
          - alertmanager:alertmanager
        extra_hosts:
          - "nonso:172.17.0.1"
          - "local:172.17.0.1"
        volumes:
          - ./blackbox/config:/etc/blackbox_exporter/
 
    alertmanager:
        image: prom/alertmanager:v0.15.0
        restart: unless-stopped
        command: --web.external-url=https://alertmanager.${MYDOMAIN}/
        deploy:
            labels:
            - "traefik.frontend.rule=Host:alertmanager.${MYDOMAIN}"
            - "traefik.port=9093"
        links:
          - cadvisor:cadvisor 
          - node-exporter:node-exporter
          - consul:consul
          - blackbox-exporter:blackbox-exporter
          - alertmanager:alertmanager
        extra_hosts:
          - "nonso:172.17.0.1"
          - "local:172.17.0.1"
        networks:
          - service
        expose:
          - 9093
        volumes:
          - ./alertmanager/config:/etc/alertmanager
                      
 
volumes:
  grafana5_data:
    driver: nfs
    driver_opts:
      share: 172.17.0.1/srv/data/volumes/grafana5_data
  grafana_data:
    driver: nfs
    driver_opts:
      share: 172.17.0.1/srv/data/volumes/grafana_data
  influxdb_data:
      driver: nfs
      driver_opts: 
        share: 172.17.0.1/srv/data/volumes/influxdb_data
  prometheus_data:
    driver: nfs
    driver_opts:
      share: 172.17.0.1/srv/data/volumes/prometheus_data

networks:
  service:
    external:
      name: swarm-service
